name: Check black-format

on: pull_request

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"